### ISSUE TITLE
Badges are not working

### ISSUE THREAD

**Issue by lindell** [alexfernandez/package-quality#52]
For example http://npm.packagequality.com/shield/babel.svg

**Comment by jcubic** [comment]
it seems that big one png work:

[![Package Quality](http://npm.packagequality.com/badge/babel.png)](http://packagequality.com/#?package=babel)

but not the small one return `{"error":"database not available"}`

**Comment by jcubic** [comment]
Looking at the source code, that error happen on any error from `packages.find` or `retrieveShield` and since the packages.find is used on big badge it need to be `retrieveShield` that for some reason can't fetch the file from img.shields.io, they service work:

![](https://img.shields.io/badge/quality-100-green.svg?)

there should be info in log.

**Comment by alexfernandez** [comment]
Thanks for this, @jcubic. @tufosa Can you look into it?

**Comment by DiegoTUI** [comment]
@jcubic @alexfernandez I will!!

**Comment by DiegoTUI** [comment]
@jcubic I believe it is fixed now. Please, check and reopen if it is not.

**Comment by jcubic** [comment]
it works, thanks.
