### ISSUE TITLE
Search does not work for scoped packages

### ISSUE THREAD

**Issue by RamonGebben** [alexfernandez/package-quality#54]
When I search for any package that is scoped under an org or username I get `404`'s.

For instance: 
`@storybook/react`

**Comment by alexfernandez** [comment]
Hi, @RamonGebben! Sorry for the delay.

@DiegoTUI is looking into a few issues due to lack of updates. Maybe this is related?

**Comment by DiegoTUI** [comment]
Hi @RamonGebben 
I found the reason for this issue here, although I didn't work out a solution yet, maybe you can help. PackageQuality looks into [NPM's registry](http://registry.npmjs.org/) for the requested package before evaluating its quality. Non-scoped packages are straightforward to get http://registry.npmjs.org/<package-name>, but scoped packages seem to work a bit different. The problem is, I haven't found a way to query the npm registry for a scoped package. Do you happen to know how to this?

**Comment by DiegoTUI** [comment]
Hi again!!

I think I found a way!! Apparently you need to escape the `/` char, but not the `@`. Like this: https://registry.npmjs.com/@storybook%2freact/ 

There is an issue open in the npm registry about this: https://github.com/npm/registry/issues/34
I'll fix it ASAP!!

**Comment by RamonGebben** [comment]
Awesome, Hopefully this will be deployed quickly!

**Comment by DiegoTUI** [comment]
I think it is solved now. Please check

**Comment by RamonGebben** [comment]
It works! Thanks for the quick work.
